export const MENU_MEALS_REQUEST = "MENU_MEALS_REQUEST";
export const MENU_MEALS_SUCCESS = "MENU_MEALS_SUCCESS";
export const MENU_MEALS_FAIL = "MENU_MEALS_FAIL";

export const MENUS_LIST_REQUEST = "MENUS_LIST_REQUEST";
export const MENUS_LIST_SUCCESS = "MENUS_LIST_SUCCESS";
export const MENUS_LIST_FAIL = "MENUS_LIST_FAIL";

export const DELETE_MENU_REQUEST = "DELETE_MENU_REQUEST";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const DELETE_MENU_FAIL = "DELETE_MENU_FAIL";

export const ADD_MENU_REQUEST = "ADD_MENU_REQUEST";
export const ADD_MENU_SUCCESS = "ADD_MENU_SUCCESS";
export const ADD_MENU_FAIL = "ADD_MENU_FAIL";

export const SUBCRIBERS_LIST_REQUEST = "SUBCRIBERS_LIST_REQUEST";
export const SUBCRIBERS_LIST_SUCCESS = "SUBCRIBERS_LIST_SUCCESS";
export const SUBCRIBERS_LIST_FAIL = "SUBCRIBERS_LIST_FAIL";