export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_INVOICES_REQUEST = "USER_INVOICES_REQUEST";
export const USER_INVOICES_SUCCESS = "USER_INVOICES_SUCCESS";
export const USER_INVOICES_FAIL = "USER_INVOICES_FAIL";

export const USER_SUBCRIBED_MENU_REQUEST = "USER_SUBCRIBED_MENU_REQUEST";
export const USER_SUBCRIBED_MENU_SUCCESS = "USER_SUBCRIBED_MENU_SUCCESS";
export const USER_SUBCRIBED_MENU_FAIL = "USER_SUBCRIBED_MENU_FAIL";